baseURL = 'https://arshadnadeem.gifts'
languageCode = 'en-us'
title = 'Arshad Nadeem Gift Counter'
theme = "hugo-theme-console"

[security.funcs]
getenv = ['^HUGO_', '^CI$', '^DEPLOYMENT_TIME$']

[params]
deploymentTime = "2024-08-13T23:00:00Z"
